sudo: required
services:
  - docker

before_install: 
  -   docker build -t jasonchong/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true jasonchong/docker-react npm run test -- --coverage