sudo: required
services:
  - docker

before_install: 
  -   docker build -t jasonchong/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true jasonchong/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "Elastic-beanstalk-test"
  env: "Elastic-beanstalk-test-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-297162400808"
  bucket_path: "Elastic-beanstalk-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"